import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-slate-950 text-base`}>
        <main className="w-11/12 md:w-5/6 max-w-4xl mx-auto py-8 md:py-12 relative">
          <div className="flex flex-col gap-6">
            <h1 className="text-4xl text-orange-600 font-bold tracking-tighter">
              Pointing Poker
            </h1>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
